spring:
  profiles:
    active: local
---

spring:
  profiles: heroku
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: jaguar.rmq.cloudamqp.com
    username: bkglyvqr
    password: xdL-64KGn4pBt46c_uwkZfXGMYsh9_-L
    virtual-host: bkglyvqr
  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  port: ${PORT:8080}
---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:cope
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  rabbitmq:
    host: moose.rmq.cloudamqp.com
    username: luxhmtsv
    password: RMKvvLs7vKgp3JOLMgM5d2w4np5jQe1G
    virtual-host: luxhmtsv
  jackson:
    serialization:
      write_dates_as_timestamps: false
