cope:
  mode: pubsub
  restful-configuration:
    server-url: http://localhost:8080
    username: something
    password: something-else
  pubsub-configuration:
    rabbit-url: moose.rmq.cloudamqp.com
    username: luxhmtsv
    password: RMKvvLs7vKgp3JOLMgM5d2w4np5jQe1G
    virtual-host: luxhmtsv
  client:
    client-id: 1234567
    software-title: KASPER
    localization-name: Kentucky
    contact-address:
      street: 1811 Somewhere Ct.
      city: Louisville
      state: Kentucky
      zip-code: 47129
    contact-phone: 502-555-5555
    locality: state

server:
    port: 10010

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

